### ISSUE TITLE
这种匹配算法速度如此慢么？跑了两个小时还是显示patchmatch matching。

### ISSUE THREAD

**Issue by PetershengWUHU** [ethan-li-coding/PatchMatchStereo#2]
![DAEGTRW7SZ~JI}%D%U13EG1](https://user-images.githubusercontent.com/39899668/88452773-fab67f80-ce93-11ea-8373-b56c2ecf7504.png)
![QQ图片20200725162624](https://user-images.githubusercontent.com/39899668/88452776-02762400-ce94-11ea-9143-6cab7e68d56e.png)

**Comment by ethan-li-coding** [comment]
PatchMatch算法速度是比较慢，但你可能是用的Debug模式，用Release模式运行，640*480大概7分钟左右。
